-- S02 data foundation: authorization helpers, audit/grant writers, grant RLS.
--
-- @up
-- Shared updated_at trigger for every pods.* configuration table.
create or replace function pods.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Inherited suite role for the caller, mirroring lib/workspace/access.mjs:
-- an org project maps organization_users.role (owner/admin/manager, else
-- member); an org-less project is owned by its creator; otherwise null.
create or replace function pods.inherited_role(p_project uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when p.organization_id is not null then (
      select case
        when lower(m.role) in ('owner', 'admin', 'manager') then lower(m.role)
        else 'member'
      end
      from public.organization_users m
      where m.organization = p.organization_id
        and m.user = auth.uid()
    )
    when p.created_by is not null and p.created_by = auth.uid() then 'owner'
    else null
  end
  from public.projects p
  where p.id = p_project;
$$;

-- GEN-RBAC-START
-- Generated by scripts/gen-rbac-sql.mjs from geiger-rbac.config.js. Do not hand-edit.
create or replace function pods.role_permissions(p_role text)
returns text[]
language sql
immutable
as $$
  select case p_role
    when 'owner' then array['*']
    when 'admin' then array['pods.overview.view', 'pods.apis.view', 'pods.usage.view', 'pods.domains.view', 'pods.connectors.view', 'pods.secrets.view', 'pods.monitoring.view', 'pods.portals.view', 'pods.audit.view', 'pods.settings.view', 'pods.roadmap.view', 'pods.route.write', 'pods.integration.write', 'pods.model.write', 'pods.authorizer.write', 'pods.gateway_response.write', 'pods.documentation.write', 'pods.deployment.create', 'pods.stage.write', 'pods.stage.promote', 'pods.stage.delete', 'pods.cache.flush', 'pods.test.invoke', 'pods.api.create', 'pods.api.update', 'pods.api.delete', 'pods.api.import', 'pods.api.export', 'pods.api_key.write', 'pods.api_key.reveal', 'pods.usage_plan.write', 'pods.secret.write', 'pods.secret.use', 'pods.client_cert.write', 'pods.trust_store.write', 'pods.waf.write', 'pods.resource_policy.write', 'pods.domain.write', 'pods.connector.write', 'pods.logs.view', 'pods.logs.data', 'pods.alarm.write', 'pods.export.write', 'pods.portal.write', 'pods.portal.publish', 'pods.sdk.generate', 'pods.connection.manage', 'pods.settings.write', 'pods.token.write']
    when 'manager' then array['pods.overview.view', 'pods.apis.view', 'pods.usage.view', 'pods.domains.view', 'pods.connectors.view', 'pods.secrets.view', 'pods.monitoring.view', 'pods.portals.view', 'pods.audit.view', 'pods.settings.view', 'pods.roadmap.view', 'pods.route.write', 'pods.integration.write', 'pods.model.write', 'pods.authorizer.write', 'pods.gateway_response.write', 'pods.documentation.write', 'pods.deployment.create', 'pods.stage.write', 'pods.stage.promote', 'pods.cache.flush', 'pods.test.invoke', 'pods.api_key.write', 'pods.usage_plan.write', 'pods.usage.view', 'pods.logs.view', 'pods.logs.data', 'pods.audit.view', 'pods.secret.use', 'pods.portal.write']
    when 'member' then array['pods.overview.view', 'pods.apis.view', 'pods.usage.view', 'pods.domains.view', 'pods.connectors.view', 'pods.secrets.view', 'pods.monitoring.view', 'pods.portals.view', 'pods.audit.view', 'pods.settings.view', 'pods.roadmap.view', 'pods.logs.view']
    else '{}'::text[]
  end;
$$;
-- GEN-RBAC-END

-- One predicate for RLS: inherited system-role keys OR product grant keys
-- (with api scope when the check names an API).
create or replace function pods.can(p_permission text, p_project uuid, p_api uuid default null)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.rbac_key_matches(
           pods.role_permissions(pods.inherited_role(p_project)),
           p_permission
         )
      or pods.rbac_allows(p_permission, p_project, 'api', p_api);
$$;

create or replace function pods.is_member(p_project uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select pods.inherited_role(p_project) is not null;
$$;

-- Server-side audit writer. audit_events has no insert policy for
-- authenticated, so user-context inserts go through here; callers must
-- redact credential-shaped keys before calling (lib/control/audit.mjs does).
create or replace function pods.audit(
  p_project uuid,
  p_actor uuid,
  p_actor_type text,
  p_action text,
  p_resource_type text,
  p_resource_id text,
  p_api uuid default null,
  p_before jsonb default null,
  p_after jsonb default null,
  p_request_id text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  -- End-user callers (auth.uid() set) may only audit projects they belong to,
  -- and only as themselves; the service role (auth.uid() null) is unrestricted.
  if auth.uid() is not null then
    if not pods.is_member(p_project) then
      raise exception 'not a member of project %', p_project using errcode = '42501';
    end if;
    if p_actor is distinct from auth.uid() or p_actor_type not in ('user', 'token') then
      raise exception 'audit actor must be the calling user' using errcode = '42501';
    end if;
  end if;
  insert into pods.audit_events (
    project_id, actor_id, actor_type, action, resource_type, resource_id,
    api_id, before, after, request_id
  ) values (
    p_project, p_actor, p_actor_type, p_action, p_resource_type, p_resource_id,
    p_api, p_before, p_after, p_request_id
  ) returning id into v_id;
  return v_id;
end;
$$;

-- Grant a product role. A grantor can never hand out a key they do not hold
-- themselves: every permission on the role is checked against the grantor's
-- own inherited keys plus their granted role keys. Raises on violation.
create or replace function pods.grant_role(
  p_project uuid,
  p_user uuid,
  p_role_key text,
  p_scope jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role_id uuid;
  v_permissions text[];
  v_inherited text[];
  v_needed text;
  v_grant_id uuid;
begin
  if not pods.can('pods.role.grant', p_project) then
    raise exception 'forbidden: pods.role.grant is required';
  end if;
  select r.id, r.permissions into v_role_id, v_permissions
  from public.roles r
  where r.project_id = p_project
    and r.key = p_role_key
    and r.deleted_at is null;
  if v_role_id is null then
    raise exception 'unknown role % for this project', p_role_key;
  end if;

  -- The grantor must hold each granted key WITHOUT a scope restriction: an
  -- inherited system-role key, or an unscoped product grant. A grant scoped to
  -- specific APIs never authorizes handing the key out more broadly.
  v_inherited := pods.role_permissions(pods.inherited_role(p_project));

  foreach v_needed in array coalesce(v_permissions, '{}'::text[]) loop
    if not (
      public.rbac_key_matches(v_inherited, v_needed)
      or pods.rbac_allows(v_needed, p_project, 'api', null)
    ) then
      raise exception 'grantor lacks permission %', v_needed;
    end if;
  end loop;

  select g.id into v_grant_id
  from pods.role_grants g
  where g.project_id = p_project
    and g.user_id = p_user
    and g.role_id = v_role_id
    and g.deleted_at is null;
  if v_grant_id is not null then
    update pods.role_grants
    set scope = p_scope, status = 'active', granted_by = auth.uid(), updated_at = now()
    where id = v_grant_id;
    return v_grant_id;
  end if;

  insert into pods.role_grants (project_id, user_id, role_id, scope, granted_by)
  values (p_project, p_user, v_role_id, coalesce(p_scope, '{}'::jsonb), auth.uid())
  returning id into v_grant_id;
  return v_grant_id;
end;
$$;

-- Revoke a product role grant (soft delete). Requires pods.role.grant.
create or replace function pods.revoke_grant(p_grant_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_project uuid;
begin
  select g.project_id into v_project
  from pods.role_grants g
  where g.id = p_grant_id and g.deleted_at is null;
  if v_project is null then
    raise exception 'unknown grant %', p_grant_id;
  end if;
  if not pods.can('pods.role.grant', v_project) then
    raise exception 'forbidden: pods.role.grant is required';
  end if;
  update pods.role_grants
  set deleted_at = now(), updated_at = now()
  where id = p_grant_id;
end;
$$;

grant execute on function pods.inherited_role(uuid) to authenticated;
grant execute on function pods.role_permissions(text) to authenticated;
grant execute on function pods.can(text, uuid, uuid) to authenticated;
grant execute on function pods.is_member(uuid) to authenticated;
grant execute on function pods.audit(uuid, uuid, text, text, text, text, uuid, jsonb, jsonb, text) to authenticated;
grant execute on function pods.grant_role(uuid, uuid, text, jsonb) to authenticated;
grant execute on function pods.revoke_grant(uuid) to authenticated;

-- Tighten the generator's permissive role_grants select: members only.
drop policy if exists role_grants_read on pods.role_grants;
create policy role_grants_read on pods.role_grants
  for select to authenticated using (pods.is_member(project_id));

-- @down
drop policy if exists role_grants_read on pods.role_grants;
create policy role_grants_read on pods.role_grants
  for select to anon, authenticated using (deleted_at is null);
revoke execute on function pods.revoke_grant(uuid) from authenticated;
revoke execute on function pods.grant_role(uuid, uuid, text, jsonb) from authenticated;
revoke execute on function pods.audit(uuid, uuid, text, text, text, text, uuid, jsonb, jsonb, text) from authenticated;
revoke execute on function pods.is_member(uuid) from authenticated;
revoke execute on function pods.can(text, uuid, uuid) from authenticated;
revoke execute on function pods.role_permissions(text) from authenticated;
revoke execute on function pods.inherited_role(uuid) from authenticated;
drop function if exists pods.revoke_grant(uuid);
drop function if exists pods.grant_role(uuid, uuid, text, jsonb);
drop function if exists pods.audit(uuid, uuid, text, text, text, text, uuid, jsonb, jsonb, text);
drop function if exists pods.is_member(uuid);
drop function if exists pods.can(text, uuid, uuid);
drop function if exists pods.role_permissions(text);
drop function if exists pods.inherited_role(uuid);
drop function if exists pods.touch_updated_at();
