-- S02 data foundation: RBAC storage.
--
-- Body generated by `@geiger/rbac` `migrationSql("pods")`, reviewed for Pods:
-- the two demo always-true write policies from the generator
-- (`roles_write` on shared public.roles, `role_grants_write`) are REMOVED.
-- Grant writes go only through pods.grant_role()/pods.revoke_grant()
-- (authz_functions migration); with no DML policy, authenticated writes fail
-- closed. The member-only select tightening for role_grants lands in the
-- authz_functions migration so this file stays a faithful generator copy.
--
-- @up
create extension if not exists pgcrypto;
create schema if not exists pods;
grant usage on schema pods to anon, authenticated, service_role;

-- Shared updated_at trigger for the authorization tables. Declared here (rather
-- than depending on a product's own touch_updated_at) so this block stands alone
-- whichever product runs it first.
create or replace function public.rbac_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Wildcard permission matching. Mirrors keys.js: "*" matches everything,
-- "<product>.*" and "<product>.<resource>.*" match by prefix, anything else is
-- an exact match. Immutable so it can be used in an index if that day comes.
create or replace function public.rbac_key_matches(p_patterns text[], p_key text)
returns boolean
language sql
immutable
as $$
  select exists (
    select 1
    from unnest(coalesce(p_patterns, '{}'::text[])) as pat
    where pat = '*'
       or pat = p_key
       or (
         right(pat, 2) = '.*'
         and left(p_key, length(pat) - 1) = left(pat, length(pat) - 1)
       )
  );
$$;

-- Shared role definitions. project_id scopes a role to one workspace; a null
-- project_id is a suite-wide template. permissions[] holds keys and wildcard
-- patterns spanning every product (events.order.refund, flow.issue.close, "*").
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  key text,
  name text not null default 'Untitled role',
  description text not null default '',
  color text not null default 'slate',
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  sort integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.roles add column if not exists key text;
alter table public.roles add column if not exists permissions text[] not null default '{}';
alter table public.roles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.roles add column if not exists deleted_at timestamptz;

create index if not exists roles_project_idx
  on public.roles (project_id) where deleted_at is null;
create unique index if not exists roles_project_key_uniq
  on public.roles (project_id, key) where key is not null and deleted_at is null;

drop trigger if exists roles_touch_updated_at on public.roles;
create trigger roles_touch_updated_at
before update on public.roles
for each row execute function public.rbac_touch_updated_at();

-- Per-product assignment. One row per (user, role) in a project. scope narrows
-- the grant to specific resources: {"event": ["<uuid>", ...]}. An empty scope
-- means the grant applies everywhere in the project.
create table if not exists pods.role_grants (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid not null,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  granted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table pods.role_grants add column if not exists scope jsonb not null default '{}'::jsonb;
alter table pods.role_grants add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table pods.role_grants add column if not exists deleted_at timestamptz;

-- The lookup rbac_allows() makes on every row of every gated query.
create index if not exists pods_role_grants_lookup_idx
  on pods.role_grants (user_id, project_id) where deleted_at is null;
create index if not exists pods_role_grants_role_idx
  on pods.role_grants (role_id) where deleted_at is null;
create unique index if not exists pods_role_grants_uniq
  on pods.role_grants (project_id, user_id, role_id) where deleted_at is null;

drop trigger if exists role_grants_touch_updated_at on pods.role_grants;
create trigger role_grants_touch_updated_at
before update on pods.role_grants
for each row execute function public.rbac_touch_updated_at();

-- The predicate every gated policy calls.
--
-- SECURITY DEFINER so a user can be authorized by grant rows they cannot
-- themselves select — otherwise the grants table's own RLS would have to be
-- open for authorization to work at all. STABLE so Postgres may cache it within
-- a statement rather than re-running it per row.
--
-- p_scope_type null  -> the permission is unscopeable; grants apply everywhere.
-- grant has no entry for p_scope_type -> that grant is unscoped. (Absence is
-- "no restriction", matching scope.js.)
create or replace function pods.rbac_allows(
  p_permission text,
  p_project uuid default null,
  p_scope_type text default null,
  p_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public, pods
as $$
  select exists (
    select 1
    from pods.role_grants g
    join public.roles r on r.id = g.role_id
    where g.user_id = auth.uid()
      and g.status = 'active'
      and g.deleted_at is null
      and r.deleted_at is null
      and (p_project is null or g.project_id = p_project)
      and public.rbac_key_matches(r.permissions, p_permission)
      and (
        p_scope_type is null
        or not jsonb_exists(g.scope, p_scope_type)
        or (
          p_scope_id is not null
          and jsonb_exists(g.scope -> p_scope_type, p_scope_id::text)
        )
      )
  );
$$;

grant execute on function pods.rbac_allows(text, uuid, text, uuid) to anon, authenticated;
grant execute on function public.rbac_key_matches(text[], text) to anon, authenticated;

alter table public.roles enable row level security;
alter table pods.role_grants enable row level security;

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
  for select to anon, authenticated using (deleted_at is null);

-- REVIEWED: the generator's demo always-true write policy for shared roles is
-- intentionally omitted. public.roles is shared suite-wide; Pods never writes
-- it directly (product roles are seeded by an admin job, not by this schema).

drop policy if exists role_grants_read on pods.role_grants;
create policy role_grants_read on pods.role_grants
  for select to anon, authenticated using (deleted_at is null);

-- REVIEWED: the generator's demo always-true write policy for role grants is
-- intentionally omitted. All grant writes go through pods.grant_role() /
-- pods.revoke_grant() (security definer, grantor-lack check inside), so with
-- no DML policy for authenticated, direct writes fail closed.

-- @down
drop policy if exists role_grants_read on pods.role_grants;
drop function if exists pods.rbac_allows(text, uuid, text, uuid);
drop table if exists pods.role_grants cascade;

-- public.roles, public.rbac_key_matches and public.rbac_touch_updated_at are
-- shared across the suite and are intentionally left in place.
